apiVersion: v1
stringData:
  token: "hvs.CAESIJ8QAlSSvPWYahnHZUnCHlMGE3OMPRSb4BiBwnUv0MXmGh4KHGh2cy5FV2hPdzNPRllWYXRrVHMxeUhaY0lSRUk"
kind: Secret
metadata:
  name: vault-token
  namespace: default
type: Opaque
