FROM oven/bun:1.2.11-alpine AS base

FROM rvolosatovs/protoc:latest AS protoc

WORKDIR /app

RUN yarn init -y && yarn add ts-proto

RUN mkdir -p ./generated

COPY ./packages/grpc_gateway/utils/nexura.proto ./

CMD ["sh", "-c", "protoc --proto_path=. --python_out=./generated --plugin=node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=esModuleInterop=true,stringEnums=true,outputServices=grpc-js --descriptor_set_out=reflection_descriptor.pb --include_imports --ts_proto_out=./generated --grpc-python_out=./generated ./nexura.proto"]


FROM base AS deps

WORKDIR /app
ARG SERVICE_NAME
COPY package.json ./
COPY ./src/${SERVICE_NAME}/package.json ./src/${SERVICE_NAME}/
COPY packages/common/package.json ./packages/common/
COPY packages/grpc_gateway/package.json ./packages/grpc_gateway/

RUN bun install --frozen-lockfile
WORKDIR /app/src/${SERVICE_NAME}
COPY --from=protoc /app/generated ./packages/grpc_gateway/generated


FROM base AS builder
ARG SERVICE_NAME
WORKDIR /app
COPY --from=deps /app/package.json ./
COPY --from=deps /app/node_modules ./node_modules
COPY packages/ ./packages/
COPY ./src/${SERVICE_NAME} ./src/${SERVICE_NAME}
WORKDIR /app/src/${SERVICE_NAME}
RUN bun prisma:generate
RUN bun run build
# CMD ["tail","-f","/dev/null"]

FROM base AS runner
WORKDIR /app

RUN addgroup -g 1001 -S bun_runner
RUN adduser -S nexura -u 1001 
ARG SERVICE_NAME
COPY --from=builder --chown=nexura:bun_runner /app/src/${SERVICE_NAME}/dist .
COPY --from=builder /app/src/${SERVICE_NAME}/src/db/ ./src/db/
ENV NODE_ENV=production
USER nexura
# CMD ["tail","-f","/dev/null"]

CMD ["bun", "index.js"]
