FROM oven/bun:1.2.11-alpine AS base

FROM rvolosatovs/protoc:latest AS protoc

WORKDIR /app

RUN yarn init -y && yarn add ts-proto

RUN mkdir -p ./generated

COPY ./packages/grpc_gateway/utils/nexura.proto ./

CMD ["sh", "-c", "protoc --proto_path=. --python_out=./generated --plugin=node_modules/.bin/protoc-gen-ts_proto --ts_proto_opt=esModuleInterop=true,stringEnums=true,outputServices=grpc-js --descriptor_set_out=reflection_descriptor.pb --include_imports --ts_proto_out=./generated --grpc-python_out=./generated ./nexura.proto"]


FROM base AS deps

WORKDIR /app

COPY package.json ./
COPY ./src/frontend/package.json ./src/frontend/
COPY packages/common/package.json ./packages/common/
COPY packages/grpc_gateway/package.json ./packages/grpc_gateway/

RUN bun install --frozen-lockfile
COPY --from=protoc /app/generated ./packages/grpc_gateway/generated


FROM base AS builder

WORKDIR /app
COPY --from=deps /app/package.json ./
COPY --from=deps /app/node_modules ./node_modules
COPY packages/ ./packages/
COPY ./src/frontend ./src/frontend/
RUN bun --filter "@nexura/frontend" build
# CMD ["bun", "run", "src/frontend/dist/index.js"]

FROM base AS runner
WORKDIR /app

RUN addgroup -g 1001 -S nexura
RUN adduser -S frontend -u 1001

COPY --from=builder --chown=frontend:nexura /app/src/frontend/.next/standalone .
ENV NODE_ENV=production
USER frontend

EXPOSE 3000

ENV PORT=3000

CMD ["bun", "src/frontend/server.js"]
