apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" . }}-db-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name:  {{ include "common.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: app-db
  data:
    - secretKey: payment-database-url
      remoteRef:
        key: nexura
        property: payment-database-url
    - secretKey: user-database-url
      remoteRef:
        key: nexura
        property: user-database-url
    - secretKey: product-database-url
      remoteRef:
        key: nexura
        property: product-database-url
    - secretKey: order-database-url
      remoteRef:
        key: nexura
        property: order-database-url
    - secretKey: cart-database-url
      remoteRef:
        key: nexura
        property: cart-database-url
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" . }}-jwt-secret
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name:  {{ include "common.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: app-jwt
  data:
    - secretKey: access-secret
      remoteRef:
        key: nexura
        property: access-secret
    - secretKey: refresh-secret
      remoteRef:
        key: nexura
        property: refresh-secret
    - secretKey: session-secret
      remoteRef:
        key: nexura
        property: session-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" . }}-frontend
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name:  {{ include "common.fullname" . }}-secretstore
    kind: SecretStore
  target:
    name: app-jwt
  data:
    - secretKey: imagekit-public-key
      remoteRef:
        key: nexura
        property: imagekit-public-key
    - secretKey: imagekit-private-key
      remoteRef:
        key: nexura
        property: imagekit-private-key
---