apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "common.fullname" .}}-secretstore
spec:
  provider: 
    vault:
      {{- toYaml .Values.config.vault | nindent 6 }}