alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "istio"
    hosts: 
      - alertmanager.duclee.store
    paths: 
    - /
    tls: 
    - secretName: monitoring-tls
      hosts:
      - alertmanager.duclee.store

grafana:
  enabled: true
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: Main Org.
      org_role: Editor
    auth:
      disable_login_form: true
  ingress:
    enabled: true
    ingressClassName: istio
    hosts:
      - grafana.duclee.store
    path: /
    tls: 
    - secretName: grafana-general-tls
      hosts:
      - grafana.duclee.store

  additionalDataSources: 
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo.monitoring:3200
    uid: tempo
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      tracesToMetrics:
        datasourceUid: prometheus

  - name: Loki
    type: loki
    access: proxy
    url: http://loki-gateway.monitoring
    jsonData:
      httpHeaderName1: "X-Scope-OrgID"
    secureJsonData:
      httpHeaderValue1: "fake"
prometheus:
  ingress:
    enabled: true
    ingressClassName: "istio"
    hosts:
      - prometheus.duclee.store
    paths: 
    - /
    tls: 
      - secretName: monitoring-tls
        hosts:
          - prometheus.nexura.store

  prometheusSpec:
    additionalScrapeConfigs: 
      - job_name: dapr-sidecars
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            regex: "true"
            source_labels:
              - __meta_kubernetes_pod_annotation_dapr_io_enabled
          - action: keep
            regex: "true"
            source_labels:
              - __meta_kubernetes_pod_annotation_dapr_io_enable_metrics
          - action: replace
            replacement: ${1}
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            replacement: ${1}
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            regex: (.*);daprd
            replacement: ${1}-dapr
            source_labels:
              - __meta_kubernetes_pod_annotation_dapr_io_app_id
              - __meta_kubernetes_pod_container_name
            target_label: service
          - action: replace
            replacement: ${1}:9090
            source_labels:
              - __meta_kubernetes_pod_ip
            target_label: __address__

      - job_name: dapr
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: keep
            regex: dapr
            source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - action: keep
            regex: dapr
            source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_part_of
          - action: replace
            replacement: ${1}
            source_labels:
              - __meta_kubernetes_pod_label_app
            target_label: app
          - action: replace
            replacement: ${1}
            source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - action: replace
            replacement: ${1}
            source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - action: replace
            replacement: ${1}:9090
            source_labels:
              - __meta_kubernetes_pod_ip
            target_label: __address__  
  