config:
  imagekit: https://ik.imagekit.io/duclee9x/
  vault:
    server: "http://100.97.111.193:8200"
    path: "kv"
    version: "v2"
    auth:
      userPass:        
        path: "userpass"
        username: "nexura"
        secretRef: 
          name: vault-user
          namespace: default
          key: "password"
