
FROM node:22-alpine 

WORKDIR /app
RUN apk add --no-cache openssl
RUN GRPC_HEALTH_PROBE_VERSION=v0.3.6 && \
    wget -qO/bin/grpc_health_probe https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/${GRPC_HEALTH_PROBE_VERSION}/grpc_health_probe-linux-amd64 && \
    chmod +x /bin/grpc_health_probe

COPY package*.json ./
RUN yarn 
COPY . .
CMD ["yarn", "dev"]

