apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: smtp
spec:
  type: bindings.smtp
  version: v1
  metadata:
  - name: host
    value: "smtp.mailgun.org"
  - name: port
    value: "465"
  - name: user
    value: "admin@mg.duclee.store"
  - name: password
    secretKeyRef:
      name: smtp-secret
      key:  smtp-password
  - name: skipTLSVerify
    value: false
  - name: emailFrom
    value: "admin@mg.duclee.store"
scopes:
- frontend
- user
- order
- workflow