apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: tracing
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "tempo.monitoring.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc
