---
{{- range $key, $val := .Values.externalSecret.secrets }}
{{- range $secretName, $secretValues := $val }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "common.fullname" $ }}-{{ $secretName }}
  namespace: {{ $secretValues.namespace}}
spec:
  refreshInterval: {{ $.Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name:  {{ include "common.fullname" $ | printf "%s-clustersecretstore" | quote }}
    kind: ClusterSecretStore
  target:
    name: {{ $secretName }}
  data:
    {{- range $item := $secretValues.values }}
    - secretKey: {{ $item.key }}
      remoteRef:
        key: {{ $item.path }}
        property: {{ $item.key }}
    {{- end }}
    {{- end }}
---
{{ end }}
