---
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: app-gateway
spec:
  selector:
    {{- toYaml $.Values.istio.gatewaySelector | nindent 4 }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: true
      hosts:
{{- range .Values.istio.services }}
        - {{ .host }}
{{- end }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ $.Values.istio.credentialName }}
      hosts:
{{- range .Values.istio.services }}
        - {{ .host }}
{{- end }}
---
{{- range .Values.istio.services }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-virtualservice" .name }}
spec:
  hosts:
    - {{ .host }}
  gateways:
    - app-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ .service }}.{{ .namespace }}.svc.cluster.local
            port:
              number: {{ .port }}
---
{{- end }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
