apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "common.fullname" . | printf "%s-clustersecretstore" | quote }}
  namespace: {{ .Values.externalSecret.clusterSecretStore.namespace }}
spec:
  provider: 
    {{- toYaml .Values.externalSecret.clusterSecretStore.provider | nindent 4 }}