---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.certName }}
  namespace: {{ .Values.certManager.namespace }}
spec:
  secretName: {{ .Values.certManager.certName | printf "%s-tls" | quote }}
  issuerRef:
    name: {{include "common.fullname" . }}-{{ .Values.certManager.issuer }}
    kind: ClusterIssuer
  dnsNames:
{{- range .Values.certManager.dnsNames }}
    - {{ . | quote}}
{{- end }}