# applicationsets/infra-applicationset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-applicationset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: external-secrets
            path: infra/external-secrets
            namespace: external-secrets
          - name: cert-manager
            path: infra/cert-manager
            namespace: cert-manager
          - name: istio-base
            path: infra/istio/base
            namespace: api-gateway
          - name: istiod
            path: infra/istio/istiod
            namespace: api-gateway
          - name: istio-gateway
            path: infra/istio/gateway
            namespace: api-gateway
          - name: dapr
            path: infra/dapr
            namespace: dapr
          - name: tempo
            path: infra/monitoring/tempo
            namespace: monitoring
          - name: loki
            path: infra/monitoring/loki
            namespace: monitoring
          - name: kube-prometheus-stack
            path: infra/monitoring/prometheus
            namespace: monitoring
          - name: k8s-monitoring
            path: infra/monitoring/k8s-monitoring
            namespace: monitoring
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/duclee9x/nexura-rendered-manifest
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
