apiVersion: v1
kind: Secret
metadata:
  name: rendered-manifest-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/duclee9x/nexura-rendered-manifest.git
  password: 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
  username: duclee9x
  project: default
 